# Generated by Django 4.2.13 on 2024-07-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='agency_em',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='contact_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary_education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_name_ext',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='father_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='gsis_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ext',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_brgy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_house_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_subd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='permanent_zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_brgy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_house_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_subd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary_education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_business_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_name_ext',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='spouse_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='sss_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='tin_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
